# Generated by Django 3.2.5 on 2021-07-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='field',
            field=models.CharField(choices=[('Development', 'Development'), ('Competetive Coding', 'Competetive Coding')], max_length=20),
        ),
    ]
